<a href="https://colab.research.google.com/github/Nikita018/Computer-Vision-problems/blob/master/Experiments%20with%20Filters/RotationMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math

In [0]:
theta=math.pi/2

In [0]:
# Rotation around X axis
Rx=np.array([[1,0,0],  
             [0,math.cos(theta), -math.sin(theta)],
             [0, math.sin(theta),math.cos(theta)]])
#print(Rx)
A = np.array([1,1,1])
#print(np.matmul(Rx,A))
# Rotation around Y axis
Ry=np.array([[math.cos(theta),0,math.sin(theta)],  
             [0,1, 0],
             [-math.sin(theta),0,math.cos(theta)]])

#print(Ry)
# Rotation around Z axis
Rz=np.array([[math.cos(theta),-math.sin(theta),0],  
             [math.sin(theta),math.cos(theta), 0],
             [0, 0,1]])
print(Rz)

[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


In [0]:
Rzy = np.matmul(Rz,Ry) # This matrix resultant will have rotation across y axis first and z axis next
print(Rzy)

[[ 3.74939946e-33 -1.00000000e+00  6.12323400e-17]
 [ 6.12323400e-17  6.12323400e-17  1.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  6.12323400e-17]]


In [0]:
Ryz=np.matmul(Ry,Rz) # This matrix resultant will have rotation across z axis first and y axis next
print(Ryz)

[[ 3.74939946e-33 -6.12323400e-17  1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00]
 [-6.12323400e-17  1.00000000e+00  6.12323400e-17]]


In [0]:
A = np.array([[10],[0],[20]])
result = np.matmul(Ryz,A)
print(result)
# Resultant after rotation in z axis and then in y axis
# Result : [20,10,0]

[[2.000000e+01]
 [1.000000e+01]
 [6.123234e-16]]


[[1 2]
 [2 1]]
[[1 2]
 [2 1]]


In [0]:
e